JPA테이블매칭이 안되는 오류를 해결했습니다.
Comp-ACT/random-lunch-menu-backend pull request #3
Opened 2022-07-24 14:05 UTC by sejoon00

## 📚 개요

> ㅈㄱㄴ

## 🕐 리뷰 예상 시간

> 2m

## ❗❗ 중요한 변경점(Option)

> 리뷰가 비교적 꼼꼼히 이루어져야할 부분이나 파일을 여기다 적어주거나 </br>
> 해당 로직에 직접 코멘트를 달아도 좋습니다

2022-07-24 15:28 UTC, Ji-InPark requested changes
리뷰 반영해주세요~

2022-07-24 15:28 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/User/Users.java
> +public class Users {
왜 users죠..?

2022-07-24 15:28 UTC, Ji-InPark commented on build.gradle
> +	implementation 'com.h2database:h2'
h2 db는 메모리 db라서 실제 구현들어갈 때는 사용하면 안돼요~

2022-07-24 15:28 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/Restaurant/Restaurant.java
> +//    private List<User> positiveUserList;
주석처리할거면 todo 같은 거 붙여서 어떤 작업할 때 이 주석에 적혀있는 구문을 사용할건지 적어주시고
아니라면 걍 지워주세요

2022-07-24 15:28 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/Room/Room.java
> +
여기 주석들도 마찬가지로 처리해주세요

2022-07-24 15:28 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/User/Users.java
> +//    private List<Long> roomId;
상동

2022-07-24 15:28 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/User/UsersRepository.java
> +public interface UsersRepository extends JpaRepository<Users,Long> {
, 뒤에 스페이스 하나 넣어주세요

2022-07-24 15:28 UTC, Ji-InPark commented on src/main/resources/application.properties
> +spring.datasource.password=
이 2개 정보는 따로 파일로 분리해서 관리하고 gitignore로 깃헙에 안올리게끔 처리해줘야할것 같네요

2022-07-24 15:28 UTC, Ji-InPark commented on src/main/resources/application.properties
> +# H2 ?? ??
이런 주석 목적이 다음에 까먹을까봐이면 차라리 이슈를 새로 발행해서 기억하는 편이 더 좋습니다.

2022-07-24 15:28 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/User/Users.java
> +        //this.roomId = roomId;
상동

2022-07-24 15:28 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/Room/Room.java
> +        this.name =name;
= 뒤에 스페이스 넣어주세요

2022-07-24 15:42 UTC, sejoon00 commented on src/main/java/com/TeamSk/JMC/Domain/Room/Room.java
> +        this.name =name;
lgtm

2022-07-24 15:42 UTC, sejoon00 commented on src/main/java/com/TeamSk/JMC/Domain/User/Users.java
> +        //this.roomId = roomId;
lgtm

2022-07-24 15:51 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/User/Users.java
> +        //this.roomId = roomId;
어허 pr 올린사람이 lgtm을 써?

2022-07-25 00:56 UTC, Ji-InPark approved these changes
나중에 application.properties 부분 보안 관련해서 찾아보고 gitignore로 따로 관리해주는 방식 한 번 찾아봐주세요.

2022-07-25 07:07 UTC, merged