JPA테이블완성
Comp-ACT/random-lunch-menu-backend pull request #4
Opened 2022-08-07 06:47 UTC by sejoon00

## 📚 개요

> ㅈㄱㄴ

## 🕐 리뷰 예상 시간

> 6m

## ❗❗ 중요한 변경점(Option)

> 리뷰가 비교적 꼼꼼히 이루어져야할 부분이나 파일을 여기다 적어주거나 </br>
> 해당 로직에 직접 코멘트를 달아도 좋습니다

2022-08-07 06:50 UTC, Ji-InPark requested changes
브랜치 왜 저번거 썼어요 ㅡㅡ
브랜치 따로 파서 다시 올려주세요

2022-08-07 06:51 UTC, sejoon00 commented
> 

그 JPA 오류해결이 아직 안됐던거 이번에 해결한거라 여기다 한거에용...

2022-08-07 06:52 UTC, Ji-InPark commented
> > 
> 
> 그 JPA 오류해결이 아직 안됐던거 이번에 해결한거라 여기다 한거에용...

그래도 다음부터는 따로 파주세요 아니면 pr 설명에라도 적어주시구요

2022-08-07 07:05 UTC, sejoon00 commented
> > > 
> > 
> > 
> > 그 JPA 오류해결이 아직 안됐던거 이번에 해결한거라 여기다 한거에용...
> 
> 그래도 다음부터는 따로 파주세요 아니면 pr 설명에라도 적어주시구요

ㅇㅋㅇㅋ입니다

2022-08-08 05:13 UTC, Ji-InPark requested changes
리뷰 반영해주세요~

2022-08-08 05:13 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/Restaurant/Restaurant.java
> +
lint를 적용하면 이런 공백이 없긴 할텐데...
java에는 적용해본적이 없어서... 일단 나중에 제가 lint 적용 pr 올려보겠습니다.

2022-08-08 05:13 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/Restaurant/Restaurant.java
> +    private String Name;
```suggestion
    private String name;
```

2022-08-08 05:13 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/Room/Room.java
> +    @Column(name = "ROOM_ID")
name을 넣어주는 기준이 있나요? restaurant에서는 안넣어줬는데 여기에는 들어있길래

2022-08-08 05:13 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/Room/Room.java
> +    private String LeaderName;
```suggestion
    private String leaderName;
```

2022-08-08 05:13 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/Room/Room.java
> +    private List<RecentRestaurant> recentRoomList;
변수명에는 list같은 애들 안쓰는게 좋긴해요
recentRooms 정도가 어떨지?

2022-08-08 05:13 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/Room/Room.java
> +    private List<RecentRestaurant> recentRoomList;
근데 왜 recentRoom이죠...?
recentRestaurants가 되어야 할거 같은데요?

2022-08-08 05:13 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/RoomUser/RoomUser.java
> +    private Room room;
여기에는 객체말고 id들만 들고 있어도 되지 않을까 생각하는데... 어떻게 생각하시나요

2022-08-08 05:13 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/User/User.java
> +    User(String age, String name)
age는 어디서 쓰는거죠? 안쓰는 파라매터라면 삭제해주세요.

2022-08-08 05:13 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/Voting/Voting.java
> +    private boolean agree_flag;
```suggestion
    private boolean agreeFlag;
```

2022-08-08 05:13 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/Voting/Voting.java
> +    private Long USER_ID;
```suggestion
    private Long userId;
```

2022-08-08 12:24 UTC, sejoon00 commented on src/main/java/com/TeamSk/JMC/Domain/User/User.java
> +    User(String age, String name)
아 builder 설명해주다가 안지웠네

2022-08-08 12:27 UTC, sejoon00 commented on src/main/java/com/TeamSk/JMC/Domain/Room/Room.java
> +    @Column(name = "ROOM_ID")
테이블에 이름이 ROOM_ID로 들어가는건데 restaurant는 까먹고 안했나보네요

2022-08-08 12:28 UTC, sejoon00 commented on src/main/java/com/TeamSk/JMC/Domain/Room/Room.java
> +    private List<RecentRestaurant> recentRoomList;
이런 실수를

2022-08-08 12:30 UTC, sejoon00 commented on src/main/java/com/TeamSk/JMC/Domain/RoomUser/RoomUser.java
> +    private Room room;
FK 설정을 객체로 안하고 id로 하는 방법은 모르겠네요

2022-08-08 12:31 UTC, Ji-InPark commented on src/main/java/com/TeamSk/JMC/Domain/RoomUser/RoomUser.java
> +    private Room room;
흠 저도 jpa는 잘 모르겠어서.. 일단 그럼 이렇게 진행하시죠

2022-08-08 12:55 UTC, Ji-InPark approved these changes
lgtm

2022-08-08 12:55 UTC, merged